--liquibase formatted sql
--changeset lizandro.alipazaga:202502202132
--comment Se modifican varias tablas agregando campos
ALTER TABLE `audimed2`.`almacen` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`almacen` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`articulos` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`articulos` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`aseguradora` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`aseguradora` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`empresa` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`empresa` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`consultorio` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`consultorio` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`especialidad` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`especialidad` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`examenes_auxiliares` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`examenes_auxiliares` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`guia_ingreso` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`guia_ingreso` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`guia_salida` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`guia_salida` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`laboratorio` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`laboratorio` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`medicoauditor` ADD COLUMN `activo` smallint DEFAULT 1;
ALTER TABLE `audimed2`.`medicoauditor` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`medicoauditor` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`medio_pago` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`medio_pago` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`orden_compra` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`orden_compra` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`orden_examenes` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`orden_examenes` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`orden_servicio` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`orden_servicio` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`paciente` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`paciente` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`perfil` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`perfil` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`procedimiento` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`procedimiento` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`profesional` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`profesional` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`proveedor` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`proveedor` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`proveedor_cuentas` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`proveedor_cuentas` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`servicios` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`servicios` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`siniestros` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`siniestros` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`tipo_servicio` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`tipo_servicio` ADD COLUMN `estadoreg` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`usuarios` ADD COLUMN `eliminado` smallint DEFAULT 0;
ALTER TABLE `audimed2`.`usuarios` ADD COLUMN `estadoreg` smallint DEFAULT 0;

--rollback ALTER TABLE `audimed2`.`almacen` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`almacen` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`articulos` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`articulos` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`aseguradora` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`aseguradora` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`empresa` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`empresa` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`consultorio` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`consultorio` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`especialidad` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`especialidad` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`examenes_auxiliares` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`examenes_auxiliares` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`guia_ingreso` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`guia_ingreso` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`guia_salida` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`guia_salida` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`laboratorio` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`laboratorio` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`medicoauditor` DROP COLUMN `activo`;
--rollback ALTER TABLE `audimed2`.`medicoauditor` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`medicoauditor` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`medio_pago` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`medio_pago` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`orden_compra` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`orden_compra` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`orden_examenes` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`orden_examenes` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`orden_servicio` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`orden_servicio` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`paciente` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`paciente` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`perfil` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`perfil` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`procedimiento` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`procedimiento` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`profesional` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`profesional` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`proveedor` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`proveedor` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`proveedor_cuentas` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`proveedor_cuentas` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`servicios` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`servicios` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`siniestros` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`siniestros` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`tipo_servicio` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`tipo_servicio` DROP COLUMN `estadoreg`;
--rollback ALTER TABLE `audimed2`.`usuarios` DROP COLUMN `eliminado`;
--rollback ALTER TABLE `audimed2`.`usuarios` DROP COLUMN `estadoreg`;