--liquibase formatted sql
--changeset lizandro.alipazaga:202502192130
--comment Se crea la tabla siniestros
CREATE TABLE `siniestros`  (
  `siniestroId` int NOT NULL,
  `aseguradoraId` int NULL DEFAULT NULL,
  `tipoComunicacionId` int NULL DEFAULT NULL,
  `fechaComunicacion` datetime NULL DEFAULT NULL,
  `motivoRegistroId` int NULL DEFAULT NULL,
  `notificante` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `parentesco` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tipoDocumentoId` int NULL DEFAULT NULL,
  `numeroDocumento` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `telefono` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `activacionServicioMedico` datetime NULL DEFAULT NULL,
  `numeroSiniestro` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tipoSiniestroId` int NULL DEFAULT NULL,
  `fechaSiniestro` datetime NULL DEFAULT NULL,
  `ubigeoSiniestro` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tipoPolizaId` int NULL DEFAULT NULL,
  `numeroPoliza` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `numeroPolizaSOAT` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `inicioVigenciaPoliza` datetime NULL DEFAULT NULL,
  `finVigenciaPoliza` datetime NULL DEFAULT NULL,
  `contratante` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `telefonoContratante` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `numeroPlaca` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `claseVehiculo` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `modeloVehiculo` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `marcarVehiculo` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `color` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `año` int NULL DEFAULT NULL,
  `tipo` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `conductor` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `telefonoConductor` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `comisaria` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `numeroLesionados` int NULL DEFAULT NULL,
  `observacion` varchar(5000) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `nombreAsegurado` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `activo` bit(1) NOT NULL,
  `CodigoServicioExterno` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `fechaSi24` datetime NULL DEFAULT NULL,
  `fechallegadaMedico` datetime NULL DEFAULT NULL,
  `local` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tienda` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  PRIMARY KEY (`siniestroId`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

--rollback DROP TABLE siniestros;
