on: 
  push:
    branches:
      - pruebas
name: 🚀 Despliegue Audimed 2.0 - Test
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME_TRAINING }}
        password: ${{ secrets.FTP_PASSWORD_TRAINING }}